name: Default CI
on: 
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm i -g gatsby && npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      env:
        NODE_OPTIONS: --unhandled-rejections=warn  # In Node15 UnhandledPromiseRejection Warnings were changed to errors. Disabled temporarily. Owning team can fix on their own convenience.
      run: npm run test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
